[package]
name = "infini-op"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
digit-layout = "0.2"

[build-dependencies]
build-script-cfg = "0.0"
bindgen = "0.70"
search-infini-tools = { version = "0.0", path = "../search-infini-tools" }
